### ISSUE TITLE
keywords.txt provides link to non-existent reference page

### ISSUE THREAD

**Issue by per1234** [TamojitSaha/LTC2633#29]
## Description
The third field of keywords.txt is used to provide Arduino Language Reference links, which are accessed from the Arduino IDE by highlighting the keyword and then selecting "Find in Reference" from the Help or right click menu. This library's keywords.txt supplies a value of `LTC2633` in one of these fields but there is no Arduino Language Reference page of that name.
https://github.com/TamojitSaha/LTC2633/blob/master/keywords.txt#L7

Reference:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywordstxt-format

## Expected Behavior
"Find in Reference" menu item to be disabled when keywords that don't have an associated Arduino Language Reference page are highlighted.

## Actual Behavior
When the LTC2633 keyword is highlighted and then the Help or right click menu is opened the "Find in Reference menu item is enabled. When that menu item is clicked you get a "Could not open the URL" error

## Possible Fix
Remove the reference link from keywords.txt.

## Steps to Reproduce
1. Install library
2. Type the word LTC2633 in the Arduino IDE
3. Double click the word to highlight.
4. Help > Find in Reference

**Comment by per1234** [comment]
@TamojitSaha why did you close this? The problem still exists. My pull request to fix it is still open, though you have created a merge conflict by editing keywords.txt since I submitted it.

If you're willing to finally merge my pull request, just say so, and I'll fix the merge conflict.

**Comment by TamojitSaha** [comment]
I am extremely sorry for this. Actually @sandeepansengupta is gonna fix the issue.

**Comment by SandeepanSengupta** [comment]
@per1234
<br/>
Sorry for the inconvenience.
<br/>
I was updating the library and updated the keyword.txt too.
<br/>
Can you please validate the current variant ?
